# -*- coding: utf-8 -*-
"""python_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXcOYSy2BSgTexLMG1BgyOTKQEjmYHsR
"""

#Lists in python
marks = [49.1,50,47,47,27]
print("marks=", marks)
print(type(marks))
print(len(marks))
print(marks[0])
print(marks[1])
ali = ["student",12,"dgk"]
#ali= "k"
age = ali[1]
print("age=" , age)
print(ali)

#list slicing

print(marks[-5:-1])
print(marks[1:5])
print(marks[1:5])
print(marks[2:3])
#mutating
marks.append(110)
marks.append(120)
#decending order
marks.sort(reverse = True)
print(marks)

#aseending order
print(marks.sort())
print(marks)

list_new = ['a' , 'b' , 'c']
list_new.sort()
print(list_new)
# reverse
list_new.reverse()
print(list_new)

#insert function
design = [12, 34, 56,66, 78]
design.insert(1,4)
print(design)
#remove function
design.remove(34)
print(design)
#pop function
design.pop(2)
print(design)

#touples
Ali = (1,12.2,12,55)
print(Ali)
print(Ali[0])
print(type(Ali))
#check indeces and print number
print(Ali.index(12.2))
#count number in touple
print(Ali.count(12))

#write a program in get favorite fruits names from user and store them in list
print("please enter 3 favorite fruits names")
favfruits = []
favfruits.append(input("enter fruit 1:"))
favfruits.append(input("enter fruit 2:"))
favfruits.append(input("enter fruit 3:"))
print("Your Favorite fruits are:" , favfruits)

# write a program and check that its palindrome or not
my_list = ["m","a","m"]

# Reverse the list
reverse_list = my_list[::-1]

# Compare both lists
if (my_list == reverse_list):
    print("List is Palindrome")
else:
    print("List is Not Palindrome")

